services:
  php:
    build:
      context: ./setup/php
    container_name: php-app
    volumes:
      - ./:/app
    working_dir: /app
    tty: true
    networks:
      - piper-net
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    networks:
      - piper-net
  qdrant:
    image: qdrant/qdrant:v1.11.0
    ports:
      - "6333:6333"   # REST API
      - "6334:6334"   # gRPC API
    volumes:
      - ./var/qdrant_storage:/qdrant/storage
    networks:
      - piper-net
volumes:
  ollama:
networks:
  piper-net:
