defaults:
  aiText: GoogleAiAdapter
  aiAudio: GoogleAiAdapter
  search: GoogleSearchAdapter
  translate: DeeplAdapter
  writer: WriteAdapter

GoogleAiAdapter:
  apiKey: YOUR-API-KEY
  model: gemini-2.0-flash
  voice: google-voice-3

GoogleSearchAdapter:
  apiUrl: https://www.googleapis.com/customsearch/v1
  apiKey: YOUR-API-KEY
  searchEngineId: YOUR-SEARCH-ENGINE-ID
  excludedSites:
    - facebook.com
    - twitter.com
    - instagram.com
    - paropakaram.com
    - youtube.com
    - pinterest.com
    - linkedin.com
    - reddit.com
    - quora.com
    - tiktok.com
    - amazon.com
    - ebay.com
    - alibaba.com
    - aliexpress.com
    - etsy.com
    - walmart.com
    - bestbuy.com
    - target.com
    - flipkart.com
    - snapdeal.com
    - olx.in
    - quikr.com

OpenAiAdapter:
  apiKey: YOUR-API-KEY


DeeplAdapter:
  apiKey: YOUR-API-KEY
  formality: default
  splitSentences: true
  preserveFormatting: false

WriteAdapter:
  path: /tmp
